### ISSUE TITLE
fix order of output files

### ISSUE THREAD

**Issue by jflot** [eeg-ebe/HaplowebMaker#37]
Right now the all.zip and coma_res.svg files are in the middle of all the individual files obtained from each marker. It would be better if they were at the very bottom of the page, since I expect that most users will only download these two files (coma_res.svg should not be included in the all.zip folder that should only contain the results of HaplowebMaker and not of CoMa; ultimately we could imagine having two zipped folders proposed to download, one with the results of the per-marker analyses and one with the results of CoMa - once it includes a statistical delineation of species based on the matrix).

**Comment by quant42** [comment]
Currently the result list gets alphabetically ordered. So where the all.zip file is located depends on the names of the input files. But anyway I think it is better to provide such a file link at the very beginning of the site so that users do not have to scroll to much in order to get/find the 'all.zip' file

**Comment by quant42** [comment]
solved with commit 40e6b23195e79c3ab780eb69bd8d7316e1837e29 / 6ec86efbdc2a3951b2b2a355b122a43de02c6e0b - all.zip and coma files are always outputted first ;)
